### ISSUE TITLE
Placeholder can not be hidden and then reshown

### ISSUE THREAD

**Issue by cjsauer** [cortexsystems/cortex-html5-base#1]
We're working on figuring out some strange placeholder behavior on one of our creatives (and I suspect that all creatives are susceptible to this). 

I have modified my `simulator.js` module to look as follows, so that I can test what happens when the data varies rapidly. It chooses a random subset of `test-data.js` at every `onData` interval.

```js
/* global window */

import TEST_DATA from './test-data.js';
import Logger from './logger.js';
import {VISIBLE_EVENT, HIDDEN_EVENT, READY_EVENT} from './events.js';

// Dispatch the cortex-ready event in 2secs.
const DISPATCH_CORTEX_READY_TIME = 2000;

// Dispatch vistar-hidden event every 5secs.
const DISPATCH_VISTAR_HIDDEN_INTERVAL = 5000;

// Send data updates every 4 seconds.
const DISPATCH_DATA_UPDATES_INTERVAL = 4000;

var test_data = TEST_DATA;

function getRandomSubarray(arr, size) {
  var shuffled = arr.slice(0), i = arr.length, temp, index;
  while (i--) {
    index = Math.floor((i + 1) * Math.random());
    temp = shuffled[index];
    shuffled[index] = shuffled[i];
    shuffled[i] = temp;
  }
  return shuffled.slice(0, size);
}

function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min)) + min;
}

class Simulator {
  run() {
    Logger.log('Running the app in simulation mode.');

    window.Cortex = {
      onData: (dsId, fun) => {
        setInterval(() => {
          var d = getRandomSubarray(test_data, getRandomInt(0, test_data.length));
          fun(d, false);
        }, DISPATCH_DATA_UPDATES_INTERVAL);
      }
    };

    setTimeout(() => {
      window.dispatchEvent(new window.Event(READY_EVENT));
      setInterval(() => {
        window.dispatchEvent(new window.Event(HIDDEN_EVENT));
        window.dispatchEvent(new window.Event(VISIBLE_EVENT));
      }, DISPATCH_VISTAR_HIDDEN_INTERVAL);
    }, DISPATCH_CORTEX_READY_TIME);
  }
}

module.exports = Simulator;
```

Then in the `view.js` file's `render()` function, I'm doing this:

```js
render() {
    Logger.log('Rendering a new view.', this.rows);
    if (!this.rows || this.rows.length === 0) {
      this.placeholder.render();
      return;
    }

    this.placeholder.hide();
    this._render();
  }
```

However, calling `placeholder.render()` over and over again results in lots of placeholder divs. See the screenshot below:

![image](https://cloud.githubusercontent.com/assets/2013873/25191182/d0a5288e-24fc-11e7-8cc9-79e72ca35fc8.png)

Is there no way to hide and then re-show the placeholder, or is this by design? If our dataset in Silo were to be updated so that data is no longer reaching this device, we'd like to make sure that the placeholder reappears. Then, if the data in Silo were again updated, via some auto-import process or manually by hand, the placeholder should again be hidden.

**Comment by cjsauer** [comment]
Here is the link to the branch that I am currently working off of for your reference:
https://github.com/seesawlabs/cortex-html5-base/tree/streeteasy-bug

**Comment by hkaya** [comment]
@cjsauer This reference implementation assumed that Placeholder.render() will be called only once, after all, the data will always be there once the initial load completes. However, I think it makes sense to prevent the Placeholder.render() to create multiple divs. See 4f277fcb001c87cecc882acc19098ec5f731d9ee for details.

I'm closing this issue for now as I think the above change addresses your problem.

Thank you!

**Comment by cjsauer** [comment]
Thanks for the reply. Could you elaborate on this:

>after all, the data will always be there once the initial load completes.

Is the data never expected to be empty after an initial load? For example, if we populate a slice with a few rows, load the creative, and then remove those rows, what shape will the data on the device take?

From our experience, it seems like Silo will always send _at least_ a device ID down. Is that true?

**Comment by hkaya** [comment]
Sorry, I was referring to this particular setup. In general, data can be empty after the initial load. This can happen when the dataset rows has expiration times set.

When your app starts for the very first time it may also receive cached data from a previous run (note the `cached` parameter in https://github.com/cortexsystems/cortex-html5-base/blob/master/src/data.js#L30). It is up to you to use this data. Depending on the data freshness requirements of the app, you can discard the in-memory state of your app and choose to act as if you have no data when you see a cached data update.

**Comment by cjsauer** [comment]
That all makes sense. Thanks for the info, Hamza!
